#!/usr/bin/env python
"""Generate joint amortizer transitions with NumPyro prior and mixed MCMC.

Each NPZ example is generated by ``Predictive(full_generative_model)`` and
then advanced with ``DiscreteHMCGibbs(NUTS(...))``. Spot counts vary across
examples; node arrays are flattened and bounded by ``n_node``/``n_edge``.
The saved ``L_prime`` and ``F_prime`` are one joint posterior draw, never
marginal pairs.
"""

from __future__ import annotations

import argparse
from pathlib import Path

import jax
import jax.numpy as jnp
import numpy as np
from numpyro.infer import DiscreteHMCGibbs, MCMC, NUTS, Predictive

from amortized_mcmc import build_graph, full_generative_model


def parse_args():
    """Parse variable-tissue and mixed-reference-chain settings."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--seed", type=int, default=0)
    parser.add_argument("--n-examples", type=int, default=1000)
    parser.add_argument("--n-spots", type=int, default=64)
    parser.add_argument("--min-spots", type=int, default=32)
    parser.add_argument("--max-spots", type=int, default=128)
    parser.add_argument("--n-genes", type=int, default=32)
    parser.add_argument("--H", type=int, default=8)
    parser.add_argument("--n-patient-effects", type=int, default=1)
    parser.add_argument("--warmup", type=int, default=25)
    parser.add_argument("--samples", type=int, default=1)
    parser.add_argument("--graph", choices=("knn", "delaunay"), default="knn")
    parser.add_argument("--k", type=int, default=6)
    return parser.parse_args()


def model_kwargs(args, graph):
    """Build static NumPyro model arguments for one tissue graph."""
    return dict(
        n_spots=args.n_spots,
        n_genes=args.n_genes,
        H=args.H,
        senders=graph.senders,
        receivers=graph.receivers,
        n_patient_effects=args.n_patient_effects,
    )


def prior_draw(key, args, graph):
    """Draw one complete prior state with NumPyro ``Predictive``."""
    predictive = Predictive(
        full_generative_model,
        num_samples=1,
        return_sites=None,
    )
    draw = predictive(key, **model_kwargs(args, graph))
    return {name: value[0] for name, value in draw.items()}


def joint_reference_draw(key, prior, args, graph):
    """Run mixed NUTS/Gibbs from one prior draw and return the final joint state."""
    kernel = DiscreteHMCGibbs(NUTS(full_generative_model))
    mcmc = MCMC(
        kernel,
        num_warmup=args.warmup,
        num_samples=args.samples,
        num_chains=1,
        progress_bar=False,
    )
    init_params = {
        name: prior[name]
        for name in ("alpha_csp", "b_phi", "v", "phi_slab", "lambda_local", "F", "L", "alpha_p")
    }
    init_params.update({f"z_{h}": prior[f"z_{h}"] for h in range(args.H)})
    mcmc.run(key, init_params=init_params, X=prior["X"], **model_kwargs(args, graph))
    posterior = mcmc.get_samples()
    z = jnp.stack([posterior[f"z_{h}"][-1] for h in range(args.H)])
    return posterior["L"][-1], posterior["F"][-1], posterior["alpha_p"][-1], posterior["phi_slab"][-1], z


def main():
    """Generate flattened variable-size graph transitions for amortizer training."""
    args = parse_args()
    if args.n_examples < 1 or args.warmup < 0 or args.samples < 1:
        raise ValueError("n-examples and samples must be positive; warmup cannot be negative")
    rng = np.random.default_rng(args.seed)
    keys = jax.random.split(jax.random.PRNGKey(args.seed), args.n_examples)
    flat_coordinates, flat_X, flat_L, flat_L_prime = [], [], [], []
    edge_index, n_node, n_edge = [], [], []
    F_values, L_prime_values, F_prime_values = [], [], []
    alpha_values, phi_values, z_values = [], [], []
    for key in keys:
        prior_key, chain_key, coord_key = jax.random.split(key, 3)
        args.n_spots = int(jax.random.randint(coord_key, (), args.min_spots, args.max_spots + 1))
        coordinates = rng.uniform(0.0, 1.0, (args.n_spots, 2)).astype(np.float32)
        graph = build_graph(coordinates, method=args.graph, k=min(args.k, args.n_spots - 1))
        prior = prior_draw(prior_key, args, graph)
        L_prime, F_prime, alpha_prime, phi_prime, z_prime = joint_reference_draw(chain_key, prior, args, graph)
        flat_coordinates.append(coordinates)
        flat_X.append(np.asarray(prior["X"]))
        flat_L.append(np.asarray(prior["L"]))
        flat_L_prime.append(np.asarray(L_prime))
        edge_index.append(np.stack((np.asarray(graph.senders), np.asarray(graph.receivers)), axis=1))
        n_node.append(args.n_spots)
        n_edge.append(graph.n_edges)
        F_values.append(prior["F"])
        L_prime_values.append(L_prime)
        F_prime_values.append(F_prime)
        alpha_values.append(alpha_prime)
        phi_values.append(phi_prime)
        z_values.append(z_prime)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    edge_offsets = []
    node_offset = 0
    for edges, node_count in zip(edge_index, n_node):
        edge_offsets.append(edges + node_offset)
        node_offset += int(node_count)
    np.savez_compressed(
        args.output,
        coords=np.concatenate(flat_coordinates, axis=0).astype(np.float32),
        X=np.concatenate(flat_X, axis=0).astype(np.float32),
        L_current=np.concatenate(flat_L, axis=0).astype(np.float32),
        L_prime=np.concatenate(flat_L_prime, axis=0).astype(np.float32),
        edge_index=np.concatenate(edge_offsets, axis=0).astype(np.int32),
        n_node=np.asarray(n_node, dtype=np.int32),
        n_edge=np.asarray(n_edge, dtype=np.int32),
        F_current=np.asarray(F_values, dtype=np.float32),
        F_prime=np.asarray(F_prime_values, dtype=np.float32),
        alpha_p=np.asarray(alpha_values, dtype=np.float32),
        phi=np.asarray(phi_values, dtype=np.float32),
        z=np.asarray(z_values, dtype=np.int32),
    )


if __name__ == "__main__":
    main()
